---
# Установка временнОй зоны
- name: Set timezone
  timezone:
    name: "{{ timezone_os }}"
# Команды на хосте 
- block:
    - name: Enable ufw 
      ansible.builtin.shell: ufw app list 
#      ansible.builtin.shell: ufw enable
    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Allow all access to tcp port "{{ allow_ports }}"
      community.general.ufw:
        rule: allow
        port: '"{{ item }}"'
        proto: tcp
      loop: "{{ allow_ports }}"
      #loop:
#        - "{{ lookup('vars','allow_ports',wantlist=True) }}"
      tags:
        - now
    - name: Allow all access to tcp port "{{ allow_ports }}"
      debug:
        msg: "{{ item  }}"
      loop: "{{ allow_ports }}"
      tags:
        - test
    - name: Allow OpenSSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow
  tags:
    - command
# Установка ntp
- block:
    - name: Install ntp package
      package:
        name: ntp
        state: present
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian" or
            (ansible_os_family == "RedHat" and
            ansible_distribution_major_version == '7')
      tags: ntp_install

    - name: Copy the ntp.conf file
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntp"
      when: ansible_os_family == "Debian"
      tags: ntp_conf

    - name: Copy the ntp.conf file
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntpd"
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version == '7'
      tags: ntp_conf

    - name: Install chrony package
      package:
        name: chrony
        state: present
      environment: "{{ proxy_env | default({}) }}"
      tags: ntp_install
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version >= '8'

    - name: Copy the chrony.conf template file
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
      notify: "restart chronyd"
      tags: ntp_conf
      when: ansible_os_family == "RedHat" and
            ansible_distribution_major_version >= '8'
  when: ntp_enabled is defined and ntp_enabled|bool
  tags: ntp


