#- name: Pull default Docker image
#  community.docker.docker_image:
#    name: "{{ default_container_image }}"
#    source: pull
#
#- name: Create default containers
#  community.docker.docker_container:
#    name: "{{ default_container_name }}{{ item }}"
#    image: "{{ default_container_image }}"
#    command: "{{ default_container_command }}"
#    state: present
#  with_sequence: count={{ container_count }}

---
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - 'all'

- name: Create directory
  ansible.builtin.file:
    path: /opt/zabbix-docker
    state: directory
    mode: '0755'

- name: Copy all
  copy:
    src: ./
    dest: /opt/zabbix-docker
    owner: root
    mode: '0644'
    directory_mode: yes

- name: Copy conf
  template:
    src: ../templates/.env_srv.j2
    dest: /opt/zabbix-docker/env_vars/.env_srv
- name: Copy conf
  template:
    src: ../templates/.env_db_pgsql.j2
    dest: /opt/zabbix-docker/env_vars/.env_db_pgsql
- name: Copy conf
  template:
    src: ../templates/.env_web.j2
    dest: /opt/zabbix-docker/env_vars/.env_web
- name: Copy conf
  template:
    src: ../templates/.env_web_service.j2
    dest: /opt/zabbix-docker/env_vars/.env_web_service
- name: Copy conf
  template:
    src: ../templates/docker-compose.yml.j2
    dest: /opt/zabbix-docker/docker-compose.yml

- name: Get container
  block:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'I execute normally'

    - name: Force a failure
      ansible.builtin.command: /bin/true

    - name: Never print this
      ansible.builtin.debug:
        msg: 'I never execute, due to the above task failing, :-('
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: 'I caught an error, can do stuff here to fix it, :-)'

- name: Run docker-compose
  shell: "cd /opt/zabbix-docker; docker-compose up -d"

- name: Restart all container
  shell: "cd /opt/zabbix-docker; docker-compose restart"
  tags:
    - restartdocker
