# Сбор информации о ВМ
---
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - 'all'

# Установите репозиторий Zabbix

- name: Add zabbix repository if CentOS
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
  when:
    - ansible_facts['distribution'] == "CentOS"


- name: Add zabbix repository if Ubuntu
  apt:
    deb: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution | lower }}{{ ansible_distribution_version }}_all.deb
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Run the equivalent of "apt-get update" as a separate step
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Install packages of zabbix-server
  apt:
    pkg:
    #- 'nginx'
    - 'php7.4'
    - 'php7.4-pgsql'
    - 'php7.4-common' 
    - 'php7.4-cli'
    - 'php7.4-fpm'
    - 'php7.4-gd'
    - 'php7.4-mysql'
    - 'php7.4'
    - 'php7.4-mbstring'
    - 'php7.4-bcmath'
    - 'php7.4-curl'
    - 'php7.4-xml'
    - 'php7.4-xmlrpc'
    - 'php7.4-zip'
    - 'php7.4-json' 
    - 'php7.4-opcache'
    - 'php7.4-readline'
    - 'php7.4-imap'
    - 'php7.4-intl'
    - 'php7.4-ldap'
    - 'php-apcu'
    #- 'php8.1-pgsql'
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-nginx-conf'
    - 'zabbix-sql-scripts'
    - 'zabbix-agent'
    state: present
  tags:
    - install
#- name: Remove php8.1
#  apt:
#    pkg:
#    - 'php8.*'
#    state: absent
#    autoremove: yes
#  tags:
#    - del
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^post_max_size ='
    line: post_max_size = 16m
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^max_execution_time ='
    line: max_execution_time = 300
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^max_input_time ='
    line: max_input_time = 300
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^bcmath ='
    line: bcmath = on
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^mbstring = '
    line: mbstring = yes
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^post_max_size ='
    line: post_max_size = 16m
  tags:
    - fixphp
- name: Change file php.ini
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^post_max_size ='
    line: post_max_size = 16m
  tags:
    - fixphp
- name: Restart zabbix server
  service: name=php7.4-fpm state=restarted
  tags:
    - fixphp
- name: Change php version
  shell: update-alternatives --set php /usr/bin/php7.4
- name: state check
  stat: path=/etc/nginx/sites-enabled/default
  register: default_file_state
  tags:
    - fixnginx
- name: Move default conf
  shell: mv /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default.enable
  when: default_file_state.stat.exists
  tags:
    - fixnginx
- name: Change file zabbix nginx conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/zabbix.conf
    regexp: '.*fastcgi_pass'
    line: fastcgi_pass    unix:/var/run/php/php7.4-fpm.sock;
  tags:
    - fixnginx
- name: Copy nginx conf
  template:
    src: roles/zabbix-server/templates/zabbix.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
  tags:
    - fixnginx
- name: Check apache2 exists
  stat: path=/etc/init.d/apache2
  register: state_apache2
- name: Stop apache
  service: name=apache2 state=stopped
  when: state_apache2.stat.exists
  tags:
    - fixnginx
- name: Restart nginx
  service: name=nginx state=restarted
  tags:
    - fixnginx
- name: Copy conf
  template:
    src: roles/zabbix-server/templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
- name: Copy php conf
  template:
    src: roles/zabbix-server/templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
- name: Restart zabbix server
  service: name=zabbix-server state=restarted
  tags:
    - restartzabbix
- name: Add line to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    #regexp: '10.143.2.58'
    line: "{{ item }} new-zabbix.testlocal"
  loop: "{{ groups.zabbix }}"
  tags:
    - hosts
- name: Check nodes
  ansible.builtin.shell:  zabbix_server -R ha_status
  tags:
    - checknodes
