- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main"
    state: present
    update_cache: no
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- name: Run the equivalent of "apt-get update" as a separate step
  become: yes
  apt:
    update_cache: yes
- name: Run the equivalent of "apt-get -f" as a separate step
  become: yes
  apt:
    state: fixed
- name: Install pg
  apt:
    name: postgresql
    state: present
- name: Install python3-psycopg2
  apt:
    name: python3-psycopg2
    state: present
- name: Start and enable services
  systemd:
    name: postgresql
    state: started
    enabled: yes
- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data
- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
