# Сбор информации о ВМ
---
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - 'all'
  tags:
    - now

# Установите репозиторий Zabbix

- name: Add zabbix repository if CentOS
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
  when:
    - ansible_facts['distribution'] == "CentOS"


- name: Add zabbix repository if Ubuntu
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  when:
    - ansible_facts['distribution'] == "Ubuntu"
- name: Run the equivalent of "apt-get update" as a separate step
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
